//
// Created by Bartek on 2022-12-22.
//

#ifndef ABSTRACTPROGRAMMINGPROJECT_OUT_ROCKETCOMPONENT_H
#define ABSTRACTPROGRAMMINGPROJECT_OUT_ROCKETCOMPONENT_H

class RocketComponent {
    int mass;   // in tons
};

#endif //ABSTRACTPROGRAMMINGPROJECT_OUT_ROCKETCOMPONENT_H
