name: Tests

on:
  push:
    branches: [master]

jobs:
  buildAndTest:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Directory
        run: cmake -E make_directory tests/build

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc-multilib python3 curl zip unzip
          sudo apt-get install -y --no-install-recommends libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev

      - name: Build
        working-directory: tests/build
        run: |
          cmake ..
          cmake --build .