name: Tests

on: push

jobs:
  buildAndTest:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        working-directory: tests
        run: |
          g++ -std=c++20 simpleTest.cpp -o test

      - name: Run
        working-directory: tests
        run: |
          ls -la
          chmod +x test
          ./test